---
sudo: required
language: python
python: 3.6
branches:
  only:
    - gh-pages
    - /.*/
addons:
  chrome: stable
  apt:
    packages:
      - libcurl4-openssl-dev

services:
  - docker

env:
  global:
    - secure: AVbwBaVtCtTQCR4KC4gqnVeYSuE+gKFy5KgVWfKmog/eSJ60nQGLgCSJEwzzA5Q80vZkh9WFn5TmVHiSnSikMCQkUXPrux7vnwxSPkeLV23Vy3gOXDqyJQKHzVzuSsw2X7ikX9EAOaD8cn4McL1TwQqQK440gS1gudwFHZDCfdnqjMAVRW9eNVxq2kOfFMm7iUOd0uHl94fPxGQzAK7H8mGLwpphoWPgwsWO/JuIKWXE0gp6yTTZ1OuK2SrB9ZC2rURWeDHN5Q7NMHIeLjfD42NuAFAN5igZ+2CtzQKRCsO9C5vnuuvfby/yMmxrBKEkbWw0GWPanyNcKZ6j8kICIWwhSUt0Hc25gBE6BOn7aijqBCeJlwMKvVgUBASdg2P23Q2jOqy2o4n9iNAHmRKZtvrpBRhzdCu7lDVn4s7VVBfUwBj/e0+E9x1g0jbwofHo8j/BTjK0iDiHnC4O/IBneATeEcFx4bG6xg5+3uBt8/mLqG1BRUAZMz6SpBGi1PlL527t2Z3w5DNyKBzLDC3rborADdaxgjYH989vHakItq3RhiT8ZRGGfpULTnVO2gmFLCHGoVxKQX2RbTm5xiQ2aj5pnnhtYwKqPGSutdyUfJyxz/Av03NnEN65mv9TioA+sWLMKUL6KeJTT1+HcO5D01ZC7cpYc/M/S+gmff6O5eg=

matrix:
  fast_finish: true
  include:
    - env: CHECK=yamllint
      if: branch != gh-pages
    - env: CHECK=slides
      if: branch != gh-pages
    - env: CHECK=site-build
      if: branch != gh-pages
    - env: CHECK=htmlproofer
    - env: CHECK=htmlproofer-internal
    - env: CHECK=pdf-generation
  allow_failures:
    - env: CHECK=htmlproofer
    - env: CHECK=slides
    - env: CHECK=pdf-generation

install:
  - sudo apt-get update
  - sudo update-ca-certificates
  - make install-conda
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - make create-env
  - source activate galaxy_training_material
  - make install
  - if [[ $TRAVIS_EVENT_TYPE == "pull_request" ]]; then export ORIGIN_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH; else export ORIGIN_BRANCH=$TRAVIS_BRANCH; fi
  - if [[ $TRAVIS_EVENT_TYPE == "pull_request" ]]; then export ORIGIN_REPO=$TRAVIS_PULL_REQUEST_SLUG; else export ORIGIN_REPO=$TRAVIS_REPO_SLUG; fi
  - echo $ORIGIN_REPO $ORIGIN_BRANCH

script:
  # Check website
  - |
    set -e
    if [ "$TRAVIS_BRANCH" == "gh-pages" ]
    then
      make check-links-gh-pages
    else
      if [ "$CHECK" == "htmlproofer" ]
      then
        make check-html
      elif [ "$CHECK" == "htmlproofer-internal" ]
      then
        make check-html-internal
      elif [ "$CHECK" == "yamllint" ]
      then
        make check-yaml
        make check-frontmatter
      elif [ "$CHECK" == "slides" ]
      then
        make check-slides
      elif [ "$CHECK" == "site-build" ]
      then
        make build
      elif [ "$CHECK" == "pdf-generation" ]
      then
        make pdf
      fi
    fi

after_success:
  - |
    if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" -a "$CHECK" == "site-build" ]
    then
      # update badges and instances and rebuild
      make annotate
      make build
      bin/publish
    fi
