sudo: required
language: python
python: 3.6

services:
  - docker

before_script:
  # dump the changed files into a file
  - git diff --name-only "${TRAVIS_COMMIT_RANGE/.../..}" > ./CHANGES.list
  # Spell checking?
  #- apt-get install -y hunspell pandoc
  #- wget https://cgit.freedesktop.org/libreoffice/dictionaries/tree/en/en_GB.aff
  #- |
  #  cat <<EOF >custom.dict
  #  seq
  #  MethylC
  #  EOF
  - pip install vl pyyaml
  - vl --version

script:
  - set -e
  # Check links
  #- find .  \( -name "*.md" -o -name "*.html" \) -not -path "./assets/reveal.js/*" | xargs -L 1 -I '{}' sh -c "echo {}; vl -t 5 -s 1000 --allow-codes 401,403,405,500 --whitelist http://localhost:8080 {}"
  # Check structure
  - ./bin/check_structure.py
  # Check docker
  - ./bin/prepare_docker_checks.py
  #- |
  #  export ROOT=$PWD
  #  while read -r DIR
  #  do
  #    echo "$DIR"
  #    cd "$DIR"
  #    docker build -f Dockerfile.old .
  #    cd $ROOT
  #    echo ""
  #  done < DOCKER_BUILDS.list
  # Once all tutorials use new docker bootstrap script use this
  - |
    while read -r DIR
    do
      echo "$DIR"
      docker build -f "$DIR/Dockerfile" .
      echo ""
    done < DOCKER_BUILDS.list

