# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Galaxy Training!"
email: your-email@domain.com
description: A collection of tutorials generated and maintained by Galaxy Community Members across the world
url: "https://galaxyproject.github.io/training-material" # the base hostname & protocol for your site, e.g. http://example.com
github_repository: "https://github.com/galaxyproject/training-material"
github_organization_name: "galaxyproject"
logo: "/assets/images/GTN.png"

# Where things are
source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     metadata
includes_dir: _includes

# Conversion
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  toc_levels: 1..2

# Figure plugin parameters
figurify:
  skip_empty: true # or false if you want to generate all figures, even those without any alt or title
  skip_layouts:
    - introduction_slides
    - tutorial_slides
    - base_slides
  skip_titles:
    - This is my super caption

# To exclude in _site
exclude:
  - shared/font-awesome/src/
  - Gemfile
  - Gemfile.lock
  - CONTRIBUTING.md
  - CONTRIBUTORS.md
  - LICENSE.md
  - README.md
  - Makefile
  - miniconda.sh
  - "**/README.md"
  - "**/*.yaml"
  - "**/*.yml"
  - "**/*.sh"
  - bin/
  - metadata/
  - templates/

# Plugins
plugins:
  - jekyll-feed
  - jemoji
