# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Galaxy Training Material"
email: your-email@domain.com
description: > #
  A collection of training material from offered Galaxy courses
url: "http://bgruening.github.io/training-material/" # the base hostname & protocol for your site, e.g. http://example.com
github_repository: "https://github.com/bgruening/training-material"
github_username: "bgruening"
logo: "/assets/images/GTN.png"

# Where things are
source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     metadata
includes_dir: _includes

# Conversion
markdown: kramdown

# Handling Reading
exclude:
  - Gemfile
  - Gemfile.lock

# Plugins
gems:
  - jekyll-feed
  - jemoji
