# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
---
title: "Galaxy Training!"
email: galaxytrainingnetwork@gmail.com
description: A collection of tutorials generated and maintained by Galaxy Community Members across the world
url: "https://galaxyproject.github.io/"
baseurl: "/training-material"
github_repository: "https://github.com/galaxyproject/training-material"
github_organization_name: "galaxyproject"
gitter_url: "https://gitter.im/Galaxy-Training-Network/Lobby"
logo: "assets/images/GTN.png"
small_logo: "assets/images/GTN-60px.png"
help_url: https://help.galaxyproject.org/
other_languages: "fr, ja, es, pt, ar"

# Where things are
source: .
destination: ./_site
plugins_dir: _plugins
layouts_dir: _layouts
data_dir: metadata
includes_dir: .

# Conversion
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  toc_levels: 1..2

# Figure plugin parameters
figurify:
  skip_empty: true  # or false if you want to generate all figures, even those without any alt or title
  skip_layouts:
    - introduction_slides
    - tutorial_slides
    - base_slides
  skip_titles:
    - Example of an image with a caption

# Icon tag config
icon-tag:
  # in tutorials
  question: fa-question-circle
  solution: fa-eye
  hands_on: fa-pencil
  comment: fa-commenting-o
  tip: fa-lightbulb-o
  objectives: fa-bullseye
  requirements: fa-check-circle
  time: fa-hourglass-end
  keypoints: fa-key
  tool: fa-wrench
  feedback: fa-comments-o
  congratulations: fa-thumbs-up
  trophy: fa-trophy
  warning: fa-warning
  details: fa-info-circle
  param-file: fa-file-o
  param-files: fa-files-o
  param-collection: fa-folder-o
  param-text: fa-pencil
  param-check: fa-check-square-o
  param-select: fa-filter
  param-repeat: fa-plus-square-o
  galaxy-eye: fa-eye
  galaxy-gear: fa-cog
  galaxy-history: fa-archive
  galaxy-library: fa-folder
  galaxy-pencil: fa-pencil
  galaxy-refresh: fa-refresh
  galaxy-barchart: fa-bar-chart
  galaxy-cross: fa-times
  galaxy-columns: fa-columns
  galaxy-tags: fa-tags
  galaxy-selector: fa-check-square-o
  galaxy-upload: fa fa-upload
  galaxy-chart-select-data: fa fa-database
  galaxy-save: fa fa-save

  # menus, links
  zenodo_link: fa-files-o
  tutorial: fa-laptop
  slides: fa-slideshare
  interactive_tour: fa-magic
  workflow: fa-share-alt
  topic: fa-folder-o
  instances: fa-cog
  docker_image: fa-ship
  galaxy_instance: fa-external-link
  references: fa-bookmark
  gitter: fa-comments
  help: fa-life-ring
  github: fa-github
  email: fa-envelope-o
  twitter: fa-twitter
  linkedin: fa-linkedin
  orcid: ai-orcid
  curriculum: fa-graduation-cap

# To exclude in _site
exclude:
  - shared/font-awesome/src/
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - CONTRIBUTING.md
  - CONTRIBUTORS.yaml
  - LICENSE.md
  - README.md
  - Makefile
  - miniconda.sh
  - "**/README.md"
  - "**/*.yaml"
  - "**/*.yml"
  - "**/*.sh"
  - bin/
  - metadata/
  - templates/
  - vendor/
  - node_modules/
include:
  - .nojekyll

# Plugins
plugins:
  - jekyll-feed
  - jekyll-environment-variables

