# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
---
title: "Galaxy Training!"
email: galaxytrainingnetwork@gmail.com
description: A collection of tutorials generated and maintained by Galaxy Community Members across the world
url: "https://training.galaxyproject.org"
baseurl: "/training-material"
github_repository: "https://github.com/galaxyproject/training-material"
github_repository_branch: "main"
gitter_url: "https://gitter.im/Galaxy-Training-Network/Lobby"
logo: "assets/images/GTNLogo1000.png"
small_logo: "assets/images/GTN-60px.png"
help_url: https://help.galaxyproject.org/
other_languages: #"fr, ja, es, pt, ar"
  en: English
  de: Deutsch
  es: Español
  zh-CN: 中文
  fr: Français
  ja: 日本語
  pt: Português
  ar: العربية

# Where things are
source: .
destination: ./_site
plugins_dir: _plugins
layouts_dir: _layouts
data_dir: metadata
includes_dir: .

javascript_bundles:
  theme:
    preload: true
    resources:
      - assets/js/theme.js
  main:
    preload: true
    defer: true
    async: true
    resources:
      - assets/js/jquery.slim.min.js   # Mandatory for bootstrap.
      - assets/js/popper.min.js        # Everywhere, dropdown menu.
      - assets/js/bootstrap.min.js     # Everywhere
      - assets/js/bootstrap-toc.min.js # Only tutorials, faqs
      - assets/js/clipboard.min.js     # Used on anything with a pre
      - assets/js/anchor.min.js        # Used on every page.
      - assets/js/main.js
      # - assets/js/list.min.js # Potentially unused?

# Conversion
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  toc_levels: 1..2


# Figure plugin parameters
figurify:
  skip_empty: true  # or false if you want to generate all figures, even those without any alt or title
  skip_layouts:
    - introduction_slides
    - tutorial_slides
    - base_slides
  skip_titles:
    - Example of an image with a caption

abbreviate:
  skip_layouts:
    - introduction_slides
    - tutorial_slides
    - base_slides

# for event pages, invite link expires after 400 uses :s
# update invite link gxy.io link here when needed: https://github.com/galaxyproject/gxy.io/blob/main/group_vars/all.yaml
slack:
  invite_link: http://gxy.io/gtn-slack  # this points to the invite link
  general_channel: https://gtnsmrgsbord.slack.com/archives/C01MNM98X9V
  social_channel: https://gtnsmrgsbord.slack.com/archives/C01EDBVMHBQ
  single_cell_channel: https://gtnsmrgsbord.slack.com/archives/C06PBRR40D7

# Events from Calendars
calendars:
  single-cell:
    url: "https://calendar.google.com/calendar/ical/galaxy.sc.cop%40gmail.com/public/basic.ics"
    tags: ['single-cell']
    organisers: ['nomadscientist']
    # Optionally, the date this calendar was added, so we don't backfill
    after: 2024-11-25



# Icon tag config
icon-tag:
  announcement: fas fa-bullhorn
  arrow-keys: fa fa-arrows
  code-in: far fa-keyboard
  code-out: fas fa-laptop-code
  cofest: fas fa-users
  comment: far fa-comment-dots
  congratulations: far fa-thumbs-up
  copy: far fa-copy
  curriculum: fas fa-graduation-cap
  details: fas fa-info-circle
  docker_image: fab fa-docker
  download: fas fa-download
  download-cloud: fas fa-cloud-arrow-down
  dropdown: fas fa-caret-down
  email: far fa-envelope
  exchange: fas fa-exchange-alt
  external-link: fas fa-external-link-alt
  switch-histories: fas fa-exchange-alt
  event: far fa-calendar
  event-date: far fa-calendar
  event-location: fas fa-location-dot
  event-cost: fas fa-tag
  feedback: far fa-comments
  galaxy-advanced-search: fas fa-angle-double-down
  galaxy-show-active: fa fa-map-marker
  galaxy-barchart: fas fa-chart-column
  galaxy-visualise: fas fa-chart-column
  galaxy-visualize: fas fa-chart-column
  galaxy-vis-config: fas fa-angle-double-left
  galaxy-viz-config: fas fa-angle-double-left
  galaxy-bug: fas fa-bug
  galaxy-chart-select-data: fas fa-database
  galaxy-clear: fas fa-times-circle
  galaxy-columns: fas fa-columns
  galaxy-multihistory: fas fa-columns
  galaxy-cross: fas fa-times
  galaxy-dataset-map: fas fa-sitemap
  galaxy-delete: fas fa-trash
  galaxy-dropdown: fas fa-caret-down
  galaxy-history-options: fas fa-bars # Replaces gear, fa-caret-down
  galaxy-eye: far fa-eye
  galaxy-gear: fas fa-cog
  galaxy-histories-activity: fas fa-hdd
  galaxy-history: fas fa-columns
  galaxy-dataset-collapse: fa fa-compress
  galaxy-history-archive: fas fa-archive
  galaxy-history-size: fas fa-database
  galaxy-history-storage-choice: fas fa-hard-drive
  galaxy-history-refresh: fas fa-arrows-rotate
  galaxy-history-input: fas fa-sign-in-alt
  galaxy-history-answer: fas fa-sign-out-alt
  galaxy-home: fas fa-home
  galaxy-info: fas fa-info-circle
  galaxy-lab: fa fa-tv
  galaxy-library: far fa-folder
  galaxy-link: fas fa-link
  galaxy-panelview: fas fa-list
  galaxy-pencil: fas fa-pencil-alt
  galaxy-refresh: fas fa-redo
  galaxy-undo: fas fa-undo
  galaxy-rulebuilder-history: fas fa-history
  galaxy-save: far fa-save
  galaxy-scratchbook: fas fa-th
  galaxy-selector: far fa-check-square
  galaxy-show-hidden: fas fa-eye-slash
  galaxy-star: far fa-star
  galaxy-tags: fas fa-tags
  galaxy-toggle: fas fa-toggle-on
  galaxy-upload: fas fa-upload
  galaxy-download: fas fa-download
  galaxy-wf-best-practices: fas fa-wand-magic-sparkles
  galaxy-wf-connection: fas fa-arrows-alt-h
  galaxy-wf-edit: fa fa-edit
  galaxy-wf-new: fas fa-plus
  galaxy-wf-report-download: fas fa-print
  galaxy-wf-options: fas fa-cog
  galaxy-workflows-activity: fas fa-sitemap
  galaxy_instance: fas fa-external-link-alt
  github: fab fa-github
  gitter: fab fa-gitter
  gtn-theme: fas fa-palette
  hall-of-fame: fas fa-users
  hands_on: fas fa-pencil-alt
  help: far fa-question-circle
  history-annotate: fas fa-comment
  history-share: fas fa-share-alt
  history-select-multiple: fas fa-check-square
  instances: fas fa-globe
  interactive_tour: fas fa-magic
  keypoints: fas fa-key
  language: fas fa-language
  last_modification: far fa-calendar
  level: fas fa-graduation-cap
  license: fas fa-balance-scale
  linkedin: fab fa-linkedin
  new-history: fas fa-plus
  notebook: far fa-file-code
  objectives: fas fa-bullseye
  orcid: fab fa-orcid
  param-check: far fa-check-square
  param-collection: far fa-folder
  param-file: far fa-file
  param-files: far fa-copy
  param-repeat: far fa-plus-square
  param-select: fas fa-filter
  param-text: fas fa-pencil-alt
  param-toggle: fas fa-toggle-on
  point-right: far fa-hand-point-right
  plus: fas fa-plus
  pref-info: fas fa-user
  pref-password: fas fa-unlock-alt
  pref-identities: far fa-id-card
  pref-permissions: fas fa-users
  pref-dataprivate: fas fa-lock
  pref-apikey: fas fa-key
  pref-cloud: fas fa-cloud
  pref-toolboxfilters: fas fa-filter
  pref-custombuilds: fas fa-cubes
  pref-signout: fa fa-sign-out
  pref-notifications: far fa-plus-square
  pref-delete: fas fa-radiation
  pref-palette: fas fa-palette
  pref-list: fas fa-list
  purl: fas fa-fingerprint
  question: far fa-question-circle
  references: far fa-bookmark
  requirements: fas fa-check-circle
  rss-feed: fas fa-rss
  save: far fa-save
  search: fas fa fa-search
  slides: fab fa-slideshare
  solution: far fa-eye
  sticky-note: fas fa-sticky-note
  subdomain: fa fa-tv
  time: fas fa-hourglass-half
  text-document: fas fa-file-alt
  tip: far fa-lightbulb
  tool: fas fa-wrench
  tool-versions: fas fa-cubes
  topic: far fa-folder
  trophy: fas fa-trophy
  tutorial: fas fa-laptop
  twitter: fab fa-twitter
  warning: fas fa-exclamation-triangle
  wf-input: fas fa-chevron-circle-right
  workflow-runtime-toggle: far fa-caret-square-up
  workflow: fas fa-share-alt
  workflow-run: fas fa-play
  video: fas fa-video
  video-slides: far fa-play-circle
  zenodo_link: far fa-copy
  version: fas fa-code-commit
  rating: far fa-star
  dataset-rerun: fas fa-arrow-rotate-right
  dataset-related-datasets: fas fa-sitemap
  dataset-visualize: fas fa-chart-bar
  dataset-save: fas fa-save
  dataset-link: fas fa-link
  dataset-question: fas fa-question
  dataset-info: fas fa-info-circle
  dataset-undelete: fas fa-trash-can-arrow-up

# To exclude in _site
exclude:
  - shared/font-awesome/src/
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules
  - CONTRIBUTING.md
  - CONTRIBUTORS.yaml
  - CODEOWNERS
  - CODE_OF_CONDUCT.md
  - LICENSE.md
  - README.md
  - Makefile
  - miniconda.sh
  - "**/README.md"
  - "**/*.sh"
  - bin/
  - metadata/
  - templates/
  - vendor/
  - node_modules/
  - .jekyll-cache/
  - snippets
  - plantuml.jar
  - "**/plantuml.jar"
  - Procfile
  - app.json
  - .venv
  # These are provided by an S3 proxy in production
  - videos/topics/
  - "wk-*/**"
include:
  - .nojekyll

# Plugins
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# An announcement to play on the home page
#announcement:
#   class: success
#   title: GTN Celebrates Pride Month
#   text: |
#     June is pride month in many countries around the world! The GTN is celebrating it by remembering the story of Alan L. Hart, a trans doctor who pioneered the use of x-ray photography in tuberculosis detection.
#
#     [Read about Alan L. Hart's contribution to M. Tuberculosis](/training-material/news/2023/06/01/hart.html){: .btn.btn-primary}
#     <a href="#" class="btn btn-success" onclick="setTheme('progress')">Activate the GTN Theme!</a>
#
#     <strong>Note:</strong> You can change your theme any time via the 'Extras' menu at the top!

# A banner image that can be displayed separately for short wide banner images. Alt text is mandatory.
# banner_image:
#   source: "https://gallantries.github.io/assets/images/smorgasbord3/png/banner-email.png"
#   link: "https://gallantries.github.io/video-library/events/smorgasbord3/?utm_source=gtn-banner&utm_medium=website&utm_campaign=smorgasbord2023"
#   alt: |
#     The Gallantries, Galaxy Training Network & Galaxy Community are happy to announce: GTN Smorgasbord 3, gxy.io/smorgasbord3 a free galaxy training event, online, from may 22-26 2023. Topics covered include SARS-CoV-2, RNA-Seq, Single Cell, Proteomics, Machine Learning, Annotation, Climate, Ecology, Cancer, RO-Crates, and more! An EU flag in the corner indicates that this event is made possible with the support of the european union. A waterman butterfly projection map adorns the other corner suggesting a world wide event. Links are included to @gtn@mstdn.science @gallantries@mstdn.science, and two twitter urls @gxyTraining and @gallantries_eu
