# Exclude jekyll-scholar for speed
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-last-modified-at

# include the fake scholar plugin to prevent "unknown tag" errors
plugins_dir: [_plugins,_plugins_dev]
