---
name: galaxy_training_material
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - ruby=2.4.1
  - jemalloc=4.4.0
  - gmp=6.1.0
  - openssl=1.0.2l
  - readline=6.2
  - yaml=0.1.6
  - zlib=1.2.8
  - yamllint=1.2.1
  - nodejs=8.8.1
  - libiconv
  - pandas=0.20.3
  - requests=2.18.4
