---
name: galaxy_training_material
channels:
  - conda-forge
  - bioconda
dependencies:
  - gcc=9
  - gxx=9
  - gmp>=6.1.2
  - jemalloc>=5.0.1
  - libiconv>=1.15
  - nodejs>=9.11.1
  - openssl>=1.0.2o
  - pandas>=0.22.0
  - pip
  - pip:
    - pathspec==0.5.6
    - oyaml
  - planemo>=0.55.0
  - readline
  - requests>=2.18.4
  - ruby=2.7
  - libffi
  - yaml>=0.1.7
  - yamllint>=1.11.0
  - zlib
  - libxml2
  - ephemeris
  - pkg-config
