---
name: galaxy_training_material
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - gmp=6.1.2
  - jemalloc=5.0.1
  - libiconv=1.15
  - nodejs=9.11.1
  - openssl=1.0.2o
  - pandas=0.22.0
  - pip:
    - mkl-fft==1.0.2
    - mkl-random==1.0.1
    - pathspec==0.5.6
  - readline=7.0
  - requests=2.18.4
  - ruby=2.4.4
  - yaml=0.1.7
  - yamllint=1.11.0
  - zlib=1.2.11
