
name: galaxy_training_material
channels:
- conda-forge
- defaults
dependencies:
- ruby=2.4.1=0
- jemalloc=4.4.0=0
- gmp=6.1.0=0
- openssl=1.0.2l=0
- readline=6.2=2
- yaml=0.1.6=0
- zlib=1.2.8=3
- yamllint=1.2.1=py36_0
