name: Lint Tutorials

concurrency:
  group: ci-tutorial-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - '**/tutorial*.md'

jobs:
  lint-tool-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Lint ğŸ”ğŸ‘ğŸ‘
        run: |
          make check-tool-links

  lint-diffs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Check for broken symlinks
        run: |
          make check-diffs
