name: Lint Workflows

concurrency:
  group: ci-wfs${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - '**/*.ga'

jobs:
  lint-workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Lint ğŸ”ğŸ‘ğŸ‘
        run: |
          make check-workflows
