name: "[Cron] Update Commit Cache"
on:
  workflow_dispatch:
  schedule:
    - cron: '45 0 * * 1'
jobs:
  runner-job:
    runs-on: ubuntu-latest
    # Only run on main repo on and PRs that match the main repo.
    if: |
      github.repository == 'galaxyproject/training-material' &&
      (github.event_name != 'pull_request' ||
       github.event.pull_request.head.repo.full_name == github.repository)
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000

      # BEGIN Dependencies
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
      - uses: actions/cache@v2
        with:
          path: |
            vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle pristine ffi
      # END Dependencies

      - name: Update commit cache
        id: generate
        run: |
          # Check if the oldest commit of the commit cache is known in this history
          last_cached_commit=$(ls metadata/git-mod-*.txt | cut -d- -f 3 | cut -d. -f 1)
          git show $last_cached_commit
          ec=$?
          if (( ec != 0 )); then
            # Worst case, we need to fetch more. just fetch everything to be safe.
            git fetch --unshallow
          fi

          bundle exec ruby bin/commit-cache-update.rb

      - name: Create Pull Request
        # If it's not a Pull Request then commit any changes as a new PR.
        uses: peter-evans/create-pull-request@v3
        with:
          title: Update Cached Commit Data
          branch-suffix: commitcache
          commit-message: Update Cached Commit Data
          add-paths: metadata/
