name: "[Video] Dry-run of Video Generation"

on:
  pull_request:
    paths:
      - 'bin/ari*'
      - 'topics/*.html'

jobs:
  runner-job:
    if: github.repository_owner == 'galaxyproject'
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      mozillatts:
        image: synesthesiam/mozillatts
        ports:
          - 5002:5002
    steps:
      # Shallow should be fine for video
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # BEGIN Dependencies
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
      - uses: actions/setup-node@v2
        with:
          node-version: '19'
      - uses: actions/cache@v2
        with:
          path: |
            vendor/bundle
            ~/.npm
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-node-
            ${{ runner.os }}-gems-
      - name: Install dependencies
        run: |
          sudo apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config # for node
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          npm install
          bundle pristine ffi
      # END Dependencies
      #

      - name: Check that all slides extract presenter notes successfully
        run: |
          find topics -name 'slides.html' -or -name introduction.html -or -name 'slides_*ES.html' | \
             xargs ./bin/filter-resource-metadata video | \
             xargs bundle exec ruby ./bin/ari-extract-script.rb

      - name: Check software versions
        run: |
          FFMPEG_PATH=$(echo "const ffmpeg = require('ffmpeg-static');console.log(ffmpeg.split('/').slice(0, -1).join('/'));" | node -)
          echo "Located FFMPEG at $FFMPEG_PATH"
          export PATH="$FFMPEG_PATH:$PATH"

          echo "Software Versions"
          $FFMPEG_PATH/ffmpeg -version
          ./node_modules/.bin/editly --version
